import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faSave,
  faFilter,
  faCog,
  faDownload,
  faRing,
  faSort,
  faAngleRight,
  faCopy,
  faArrowUp,
  faArrowDown,
  faTimes,
  faTimesCircle,
  faSortAmountDownAlt,
  faSortAmountUpAlt,
  faGlobe,
  faBuilding,
  faSquare,
  faMoneyBill,
  faAt,
  faAngleUp,
  faHashtag,
  faMapMarkerAlt
} from '@fortawesome/free-solid-svg-icons'
import { faTwitter, faFacebookF, faLinkedinIn } from '@fortawesome/free-brands-svg-icons'

library.add(
  faSave,
  faFilter,
  faCog,
  faDownload,
  faRing,
  faSort,
  faAngleRight,
  faCopy,
  faArrowUp,
  faArrowDown,
  faTimes,
  faTimesCircle,
  faSortAmountDownAlt,
  faSortAmountUpAlt,
  faGlobe,
  faBuilding,
  faSquare,
  faMoneyBill,
  faTwitter,
  faFacebookF,
  faLinkedinIn,
  faAt,
  faAngleUp,
  faHashtag,
  faMapMarkerAlt
)
